KB = 1024
MB = KB * KB
GB = MB * MB

DEFAULT_MAX_SIMULTANEOUS_OBJECT_RETRIEVERS = 10
DEFAULT_MAX_SIMULTANEOUS_DOWNLOADERS = 10
DEFAULT_MAX_SIMULTANEOUS_PART_HANDLERS = 3
MAX_SIZE_OF_OBJECT = 50 * MB
DEFAULT_PART_SIZE = 10 * MB
