KB = 1024
MB = KB * KB
GB = MB * KB

DEFAULT_MAX_SIMULTANEOUS_OBJECT_RETRIEVERS = 100
DEFAULT_MAX_SIMULTANEOUS_OBJECT_SIGNERS = 10
DEFAULT_MAX_SIMULTANEOUS_DOWNLOADERS = 10
DEFAULT_MAX_SIMULTANEOUS_PART_HANDLERS = 3
DEFAULT_PART_SIZE = 10 * MB
